server:
  port: 8080

spring:
  application:
    name: calling-orchestrator
  datasource:
    url: jdbc:h2:mem:calldb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}
  auth:
    token: ${TWILIO_AUTH_TOKEN}

logging:
  level:
    com.projectname: DEBUG 